// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    breadcrumbs: '_1gLFeS6TzpCK9lx57AG3uT',
} as const;

export type ClassName = string;

export default styles;