npmScopes:
    dhampirjs:
        npmRegistryServer: ${DHAMPIR_NPM_REGISTRY}
        npmAlwaysAuth: "true"
        npmAuthToken: ${DHAMPIR_NPM_ACCESS_TOKEN}
nodeLinker: node-modules
cacheFolder: "./.yarn/cache"
