npmScopes:
    dhampirjs:
        npmRegistryServer: ${DHAMPIR_REGISTRY_SERVER}
        npmPublishRegistry: ${DHAMPIR_PUBLISH_REGISTRY}
        npmAlwaysAuth: "true"
        npmAuthToken: ${DHAMPIR_PUBLISH_TOKEN}
nodeLinker: node-modules
cacheFolder: "./.yarn/cache"
