// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    breadcrumbs: '_3UVDiDIbDEBPy5PgNNTTQb',
} as const;

export type ClassName = string;

export default styles;